### ISSUE TITLE
Gameguard-patcher script (no_gg_jp.py) does not work with python 3.10

### ISSUE THREAD

**Issue by Stefan240** [ricochhet/Erupe#11]
As I updated the documentation for installing this server I ran into a problem. Using python script for patching GameGuard out of the mhf.exe ([This script](./archive/no_gg_jp.py) does not work, when the user installed python 3.10. Running the script just throws this error:
```
***
Failed to load the Frida native extension: DLL load failed while importing _frida: The specified module could not be found.
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "C:\Users\$USER\Desktop\Launcher\no_gg_jp.py", line 12, in <module>
    import frida
  File "C:\Users\$USER\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\__init__.py", line 24, in <module>
    raise ex
  File "C:\Users\$USER\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\__init__.py", line 7, in <module>
    import _frida
ImportError: DLL load failed while importing _frida: The specified module could not be found.
```
Either the script or frida itself is not compatible with python 3.10 as it seems. My guess would be the script, but I sadly don't really know python. An easy workaround her is to use python 3.8 for the time being. I added how to install python 3.8 for now until this is fixed.

**Comment by ricochhet** [comment]
Did you try updating Frida? It seems like it could be complaining it's outdated.

**Comment by Stefan240** [comment]
It is the newest version availiable. See pip list: 
```
Package    Version
---------- -------
frida      15.1.14
pip        21.3.1
setuptools 58.1.0
```
According to a) [pypi](https://pypi.org/project/frida/) and b) [fridas GitHub](https://github.com/frida/frida) this is the newest version you can have. It is installed with either python 3.8 or python 3.10. 3.8 works, while 3.10 does not. 

There are two possibilities from here: 

Either frida changed how it works (which is unlikely since it works on 3.8), or python works a bit different in 3.10 compared to 3.8 breaking the script. 

So the script needs reworking to function properly would be my guess. Generally another solution exists, though brings its own problems with it. There is a patched EXE floating around, which seems to have disabled Gameguard in the exe itself. This has a few good sides and a negative. 

The good: 
- It does not need to be patched each and every time the game is started
- locale emulator can be used to solve the Text-problems in the warning boxes and such, without to touch ones locale. 

The bad: 
- Windows defender likes to flag this exe as harmful. (Though from testing it, it seems fine)
- We can not be sure if it was tampered with in any other way as well.

**Comment by ricochhet** [comment]
It's doubtful to have been tampered with in any way other than to simply remove gameguard. The method to patch the exe has been documented somewhere before as well, I don't remember where though.

**Comment by Stefan240** [comment]
The real problem is rather that windows defender is being stupid about the patched exe removing it by any chance it can get. You can work around by adding an exeption to the folder where the exe is, but it is annoying nonetheless, when you want people to download that thing. 

Also I don't know some legal precaution would be necessary before releasing a patched exe like that

**Comment by DaraAmadyura** [comment]
Was scrolling through and noticed this, wondering if there'd be any advantage to upgrading the script to Python 3.10 compatibility? Was looking through the basic changes between 3.9 and 3.10; if someone were to rework the script, would it just be some syntax reworks, or would someone have to restructure the whole thing? Just wondering if anyone has tried to debug this issue yet
