### ISSUE TITLE
I can't connect to the webste

### ISSUE THREAD

**Issue by YufaWishui** [ricochhet/Erupe#24]

**Comment by YufaWishui** [comment]
HTTP 404

**Comment by StarGrabberDee** [comment]
If i remember correctly All of the Websites except for the Monster and the Base Website was taken down upon the game's Closing sometime ago

**Comment by Stefan240** [comment]
> If i remember correctly All of the Websites except for the Monster and the Base Website was taken down upon the game's Closing sometime ago

I mean yeah But I guess the issue is reffering to the client not being able to reach the self-hosted server for some reason. Resulting in 404

**Comment by YufaWishui** [comment]
> > If i remember correctly All of the Websites except for the Monster and the Base Website was taken down upon the game's Closing sometime ago
> 
> I mean yeah But I guess the issue is reffering to the client not being able to reach the self-hosted server for some reason. Resulting in 404

Yes exactly can you please help me to fix this?

**Comment by StarGrabberDee** [comment]
If anything check your Host Files and make sure you didnt put # infront of the Links for the Websites. That would cause them to not connect at all to the server

**Comment by YufaWishui** [comment]
Thank you I'll see if that works

**Comment by YufaWishui** [comment]
It worked now I am met with a cat that when I press the button it closes the program

**Comment by Stefan240** [comment]
> It worked now I am met with a cat that when I press the button it closes the program

did you have another server running before? If yes try clearing IE-Cache as listed here: https://github.com/ricochhet/Erupe/blob/master/docs/Troubleshooting.md#general-tips Otherwise make sure the IP of the server and the entry in hosts file match, for local testing it would be 127.0.0.1

**Comment by YufaWishui** [comment]
No this my first time running this server am I supposed to instal pgInstaller or that elephant app?

**Comment by Stefan240** [comment]
> No this my first time running this server am I supposed to instal pgInstaller or that elephant app?

You will need a database-server. if you followed the guide correctly you should have installed already. Did you leave leave the server running in the powershell after typing `go run .` ?

**Comment by YufaWishui** [comment]
I dont even have a go run option anywhere
Am I supposed to install the server

**Comment by YufaWishui** [comment]
All I did was the client

**Comment by Stefan240** [comment]
> I dont even have a go run option anywhere Am I supposed to install the server

If you want to run the game yes *a server* is necessary. Though it is on you to decide if you want to host your own one or join one that a friend might be hosting. You need a working server in order to get into the game.

**Comment by YufaWishui** [comment]
ok thx ill come back if i have any questions

**Comment by StarGrabberDee** [comment]
Happy hunting!  I just got HR7 and now i need to figure out how to get G-Rank and Extreme Style!

**Comment by YufaWishui** [comment]
Okay so I need help setting up the server side my discord is yufa#1922

**Comment by YufaWishui** [comment]
I tried to run the server but when I do that, and launch MHFZ I still get the cat and have to close it

**Comment by YufaWishui** [comment]
goroutine 1 [running]:
go/constant.StringVal({0xad9d10, 0xc0000ab898})
        c:/go/src/go/constant/value.go:486 +0xc8
cmd/compile/internal/noder.(*noder).structType(0xc00037cc40, 0xc0000d9800)
        c:/go/src/cmd/compile/internal/noder/noder.go:918 +0x357
cmd/compile/internal/noder.(*noder).expr(0xc00037cc40, {0xad4830, 0xc0000d9800})
        c:/go/src/cmd/compile/internal/noder/noder.go:778 +0x4fe
cmd/compile/internal/noder.(*noder).typeExpr(...)
        c:/go/src/cmd/compile/internal/noder/noder.go:881
cmd/compile/internal/noder.(*noder).typeExprOrNil(...)
        c:/go/src/cmd/compile/internal/noder/noder.go:890
cmd/compile/internal/noder.(*noder).typeDecl(0xc00037cc40, 0xc0000e9d40)
        c:/go/src/cmd/compile/internal/noder/noder.go:514 +0x6a
cmd/compile/internal/noder.(*noder).decls(0xc00037cc40, {0xc0000dc300, 0x10, 0x1})
        c:/go/src/cmd/compile/internal/noder/noder.go:328 +0x47b
cmd/compile/internal/noder.(*noder).node(0xc00037cc40)
        c:/go/src/cmd/compile/internal/noder/noder.go:285 +0xb8
cmd/compile/internal/noder.LoadPackage({0xc0000e0110, 0x1, 0x0})
        c:/go/src/cmd/compile/internal/noder/noder.go:85 +0x358
cmd/compile/internal/gc.Main(0x9ae380)
        c:/go/src/cmd/compile/internal/gc/main.go:192 +0xb2e
main.main()
        c:/go/src/cmd/compile/main.go:55 +0xdd\

This is where I am now.

**Comment by YufaWishui** [comment]
Can someone please help me in discord that know how to set up the server side my discord is yufa#1922

**Comment by StarGrabberDee** [comment]
I can possibly help when i get home. Or just Reference the Guide That they have up as well https://github.com/ricochhet/Erupe/blob/master/docs/Windows-Server-Install.md

**Comment by YufaWishui** [comment]
my problem is that I get a cat when I boot up the mhf script and I have to close it

**Comment by StarGrabberDee** [comment]
You mean when you launch the Server? Did you When you open the Launcher Hit the Config Button and Disable High-Grade Graphics?

**Comment by YufaWishui** [comment]
When I launch the no_gg_jp.py script amd when it opens the MHFZ app it show a Cat that has JP text and a blue button then I have to close it

**Comment by YufaWishui** [comment]
I get this..
![149575135-e8752eb8-240f-4dc7-aa78-e622c42a0459](https://user-images.githubusercontent.com/97856642/150028282-bccec38a-62f0-47c4-98b7-962b74bad7cb.png)
.

**Comment by StarGrabberDee** [comment]
You run the Server first then Run the Game?

**Comment by YufaWishui** [comment]
and how would I run the server first? I get this when I hit go run .

goroutine 1 [running]:
go/constant.StringVal({0xad9d10, 0xc0000ab898})
c:/go/src/go/constant/value.go:486 +0xc8
cmd/compile/internal/noder.(*noder).structType(0xc00037cc40, 0xc0000d9800)
c:/go/src/cmd/compile/internal/noder/noder.go:918 +0x357
cmd/compile/internal/noder.(*noder).expr(0xc00037cc40, {0xad4830, 0xc0000d9800})
c:/go/src/cmd/compile/internal/noder/noder.go:778 +0x4fe
cmd/compile/internal/noder.(*noder).typeExpr(...)
c:/go/src/cmd/compile/internal/noder/noder.go:881
cmd/compile/internal/noder.(*noder).typeExprOrNil(...)
c:/go/src/cmd/compile/internal/noder/noder.go:890
cmd/compile/internal/noder.(*noder).typeDecl(0xc00037cc40, 0xc0000e9d40)
c:/go/src/cmd/compile/internal/noder/noder.go:514 +0x6a
cmd/compile/internal/noder.(*noder).decls(0xc00037cc40, {0xc0000dc300, 0x10, 0x1})
c:/go/src/cmd/compile/internal/noder/noder.go:328 +0x47b
cmd/compile/internal/noder.(*noder).node(0xc00037cc40)
c:/go/src/cmd/compile/internal/noder/noder.go:285 +0xb8
cmd/compile/internal/noder.LoadPackage({0xc0000e0110, 0x1, 0x0})
c:/go/src/cmd/compile/internal/noder/noder.go:85 +0x358
cmd/compile/internal/gc.Main(0x9ae380)
c:/go/src/cmd/compile/internal/gc/main.go:192 +0xb2e
main.main()
c:/go/src/cmd/compile/main.go:55 +0xdd\

**Comment by StarGrabberDee** [comment]
How did you set up Your Server What Steps did you do?
The Error message is saying you're not connected to the internet.

**Comment by YufaWishui** [comment]
The same way I was instructed

**Comment by StarGrabberDee** [comment]
Hm When I get home ill See if i can help if noone else does

**Comment by StarGrabberDee** [comment]
I added you on Discord i can see what i can do

**Comment by ricochhet** [comment]
When you get to it, please provide your solution here before closing this issue.

**Comment by StarGrabberDee** [comment]
Was just editing the Config.go file and not the config.json

**Comment by JerCoolDude** [comment]
Im having the same issue except my server seemingly starts just fine but I still get the 404 screen. In the hosts file I removed the #'s for the addresses I added but it didn't help

**Comment by StarGrabberDee** [comment]
> 
Were you editing the .Json File or the .Go File. 
Do not Edit the .Go File in Config. The file you Edit will be the .Json file when youre setting up the server parts.

**Comment by JerCoolDude** [comment]
> > 
> 
> Were you editing the .Json File or the .Go File. Do not Edit the .Go File in Config. The file you Edit will be the .Json file when youre setting up the server parts.

I was editing the .json file

**Comment by JerCoolDude** [comment]
I might have put my external IPV4 in the wrong place in the config though. Where exactly do I need to put that? I currently have it at the very top of the config after "host_ip"

**Comment by StarGrabberDee** [comment]
> 

Are you playing it on the Same machine?? If you are you dont have to change the IP for any of the slots only the password for PostGres.

**Comment by JerCoolDude** [comment]
Yeah I'm playing on the same machine, but even if I change "host_ip" to 127.0.0.1 and leave "host" as localhost it still gives me the 404 screen.

**Comment by StarGrabberDee** [comment]
For the Server IPs you didnt change those did you? You left everything the same? 
The ones under These here. 
![image](https://user-images.githubusercontent.com/97332029/150586289-55104b0e-e5d3-40f0-bfcb-7022a80545ea.png)

**Comment by JerCoolDude** [comment]
No I didnt change those

**Comment by JerCoolDude** [comment]
could there be an issue with my server? the cmd says:
`2022-01-22T03:07:04.311+0800    INFO    main    Erupe-master/main.go:34 Starting Erupe
2022-01-22T03:07:04.362+0800    INFO    main    Erupe-master/main.go:62 Connected to database
2022-01-22T03:07:04.623+0800    INFO    main    Erupe-master/main.go:85 Started launcher server.
2022-01-22T03:07:04.625+0800    INFO    main    Erupe-master/main.go:98 Started entrance server.
2022-01-22T03:07:04.625+0800    INFO    main    Erupe-master/main.go:111        Started sign server.
2022-01-22T03:07:04.625+0800    INFO    main    Erupe-master/main.go:125        Started channel server.
127.0.0.1 - - [22/Jan/2022:03:08:06 +0800] "GET /serverlist.xml HTTP/1.0" 200 108`

**Comment by StarGrabberDee** [comment]
Oh thats odd its saying youre connecting to the server. One sec let me see something

**Comment by StarGrabberDee** [comment]
Are you Running the no_gg_jp.py with Admin rights?

**Comment by JerCoolDude** [comment]
yeah I open the cmd as administrator

**Comment by JerCoolDude** [comment]
then I type cd "location of no_gg_jp.py" and then I run it from there

**Comment by StarGrabberDee** [comment]
Yeah your server is running but some reason the Client is giving you a 404.  I'll have to dig deeper into it. From the previous guy was missing a bit of things also had him Downgrade to Python ?.7  instead of 8. Also installed Frida in Powershell.  That ended up helping him get online. I'll have to get home and check some notes. Someone else might get to this before me though

**Comment by JerCoolDude** [comment]
oh, thank you that worked

**Comment by StarGrabberDee** [comment]
Simpliest Solution is the one thats never on your mind. Lol Happy hunting!
