### ISSUE TITLE
【ERROR】Step 5: Run the Client Patcher

### ISSUE THREAD

**Issue by ShibainuTen** [ricochhet/Erupe#61]
The "Windows-Server-Install.md" procedure is not successful, what should I do?

`E:\MHF\client\MHF-ZZ_Installed_Files>py no_gg_jp.py
Traceback (most recent call last):
  File "no_gg_jp.py", line 143, in <module>
    main()
  File "no_gg_jp.py", line 18, in main
    pID = frida.spawn(executable_name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\frida\__init__.py", line 57, in spawn
    return get_local_device().spawn(*args, **kwargs)
  File "C:\Users\useru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\frida\core.py", line 149, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.NotSupportedError: unable to spawn executable at 'mhf.exe': 0x000002e4`

**Comment by ShibainuTen** [comment]
My environment is
-Windows10 Home 64bit 
-python 3.8.10
-frida 15.1.17

**Comment by ShibainuTen** [comment]
Sorry, this link solved the problem.
[/issues/49]
